# Generated by Django 4.2.13 on 2024-06-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='thumb',
            field=models.FileField(blank=True, default='default.md', upload_to=''),
        ),
    ]
