# Generated by Django 4.2.13 on 2024-06-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='thumb',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
